name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run Avenue_Cypress/
        uses: cypress-io/github-action@v5
        # after the test run completes store videos and any screenshots
      - uses: actions/upload-artifact@v3
      # add the line below to store screenshots only on failures
        if: failure()
        with:
         name: cypress-screenshots
         path: cypress/screenshots


        
