name: End-to-end tests
on: push
jobs:         
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v3

      - name: Configurar Cypress e executar testes
        env:
          CYPRESS_PACKAGE_VERSION: Avenue_Cypress/package-lock.json
        uses: cypress-io/github-action@v5        
