name: End-to-end tests
on: push
jobs:                   
  cypress-run-old:
    name: Cypress run old
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          project: ./Avenue_Cypress/
          
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          spec: Avenue_Cypress/cypress/e2e/amazon.cy.js
